import type { Metadata } from "next";
import RootLink from "@/components/Router";
import React from "react";
import OnClickRooting from "@/components/OnClickRooting";
import '@/app/globals.css';


export const metadata: Metadata = {
  title: "scheduler_for_mj",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;

}

export default function RootLayout({children}:Props) {
  return (
<>
<html lang="ja">
  <body>
    <div className="flex">
      <div className="w-1/6 grid grid-cols-1 text-center bg-[#EEFFFF]">
        <h1 className="text-[24px]">menu</h1>
        <OnClickRooting
        root = "/"
        displayWord="TOPPAGE"
        />
        <OnClickRooting
        root = "/schedule"
        displayWord="schedule"
        />
        <OnClickRooting
        root = "/result"
        displayWord="result"
        />
      </div>
      <div className="w-5/6 bg-[#BAD3FF]">
        {children}
      </div>
    </div>
  </body>
</html>
</>
  );
}
