import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "scheduler_for_mj",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;

}

export default function RootLayout({children}: Props) {
  return (
    <>
      <Head>
        <title>charts-sample</title>
      </Head>
      <div className={'flex min-h-100vh'}>
        さいど
  
        <div className={'flex flex-col flex-grow bg-gray-800'}>
          さいど？

          <main className={'bg-gray-800 flex-grow p-20'}>{children}</main>
        </div>
      </div>
    </>
  );
}
